#!/bin/sh -e

case "$1" in
    configure)
	if ! getent passwd slimserver >/dev/null; then
	    adduser --disabled-password  --quiet --system \
		--home /usr/share/slimserver --no-create-home \
		--gecos "RealtimeKit" --group slimserver
	fi

     	test -d /var/lib/slimserver/Firmware || mkdir /var/lib/slimserver/Firmware
	cp -u /usr/share/slimserver/firmware/* /var/lib/slimserver/Firmware

	chown -R slimserver:slimserver /var/log/slimserver /var/lib/slimserver

	;;
    abort-upgrade|abort-remove|abort-deconfigure)
	;;
    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
